### PR TITLE
Adding tests and code editing

### PR DESCRIPTION
**Pull request by Szmajasz**
Added tests and changed code a bit. Changed regr and classic to regression and classification. Edited code to keep it clean.

### CODE REVIEW

**Review by kozaka93 — COMMENTED** [review]
It's okay, but maybe we don't need the .Rhistory file.

**Comment by Szmajasz** [comment]
Good point, we can delete that file

**Review by kozaka93 — COMMENTED** [review]
It's ok

**Review by lhthien09 — APPROVED** [review]
I sent Szymons my newest versions of make_lightgbm and make_xgboost. Szymons made some changes in the punctuation, which increase the readability of the code. We sit together to check it yesterday.

**Pull request merged**
